import lattice2SubLink          as SubLink
import lattice2ShapeInfoFeature as ShapeInfoFeature
import CompoundFilter2          as CompoundFilter
import FuseCompound2            as FuseCompound    
import lattice2MultiCut         as MultiCut
import lattice2Downgrade        as Downgrade 
import lattice2BoundBox         as BoundBox   
import lattice2ShapeString      as ShapeString
import lattice2MakeCompound     as MakeCompound
import lattice2ParaSeries       as ParaSeries
import lattice2TopoSeries       as TopoSeries
import lattice2SeriesGroup      as SeriesGroup
import lattice2Slice            as Slice